# Generated by Django 4.0.4 on 2022-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.TimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
